name: Build OpenWrt APK-2 (Architecture All)

on:
  push:
    tags: [ "v*" ] # 当推送以 v 开头的标签时触发发布
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Initialization Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gawk git gettext libncurses5-dev libssl-dev xsltproc wget unzip zstd

      - name: Download SDK
        run: |
          # 1. 创建目标目录
          mkdir sdk
          
          # 2. 下载并解压（.tar.zst 格式，使用 zstd）
          SDK_URL="https://downloads.immortalwrt.org/snapshots/targets/qualcommax/ipq807x/immortalwrt-sdk-qualcommax-ipq807x_gcc-14.3.0_musl.Linux-x86_64.tar.zst"
          wget -qO- $SDK_URL | tar -I zstd -xf - -C sdk --strip-components=1
          
      - name: Add Package to SDK
        run: |
          mkdir -p sdk/package/luci-app-iptv-scan
          # 仅拷贝源码文件，避免将 SDK 自身循环拷贝
          cp -r Makefile luasrc root sdk/package/luci-app-iptv-scan/
          ls -R sdk/package/luci-app-iptv-scan/

      - name: Update & Install Feeds
        run: |
          cd sdk

          # 更新 feeds，即使某个源报错也继续执行
          ./scripts/feeds update -a || true
          
          # 安装依赖
          ./scripts/feeds install -a
          make defconfig
          # 编译插件，添加 USE_APK=y 以生成 .apk 包
          make package/luci-app-iptv-scan/compile V=s USE_APK=y

      - name: Organize Artifacts
        run: |
          mkdir -p deploy
          # 查找生成的 .apk 文件
          find . -type f -name "luci-app-iptv-scan*.apk" -exec cp {} deploy/ \;
          
          # 检查是否找到文件
          if [ -z "$(ls -A deploy)" ]; then
             echo "错误：未找到编译生成的 APK 文件，请检查编译日志！"
             exit 1
          fi

      - name: Upload to Actions
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-iptv-scan-universal-apk
          path: deploy/*.apk

      - name: Release to GitHub
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: deploy/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
